name: Test Schema
on:
    - push
    - pull_request
jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup
        run: |
            sudo apt update -q
            sudo apt install -yy python3 python3-pip graphviz
            pip install -r tools/requirements.txt
      -
        name: Build
        run: |
            ./tools/schema-merge.py
            ./tools/mkdocs build -d site
      -
        name: Validate
        run: |
            ./tools/schema-validate.py --html site/specs
